apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hf039usf8-dotnet-basic
  janus-idp.io/tekton: hf039usf8-dotnet-basic
  backstage.io/kubernetes-id: hf039usf8-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hf039usf8-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
